USE gifts_db;

INSERT INTO gifts (gift_name, gift_style) VALUES 
('A tee', 'Simple'),
('acid-washed jacket', 'Simple'),
('after-school jacket', 'Cool'),
('annyeong tee', 'Simple'),
('anorak jacket', 'Simple'),
('apron', 'Simple'),
('argyle vest', 'Simple'),
('athletic jacket', 'Active'),
('baggy shirt', 'Simple'),
('baseball shirt', 'Active'),
('basketball tank', 'Active'),
('bear tee', 'Active'),
('big-star tee', 'Simple'),
('biker jacket', 'Cool'),
('bomber-style jacket', 'Cool'),
('bonjour tee', 'Simple'),
('bug aloha shirt', 'Cool'),
('bulldog jacket', 'Cool'),
('business suitcoat', 'Cool'),
('cafe uniform', 'Elegant'),
('camo bomber-style jacket', 'Cool'),
('camper tee', 'Simple'),
('cardigan-shirt combo', 'Simple'),
('career jacket', 'Simple'),
('cavalier shirt', 'Elegant'),
('chefs outfit', 'Simple'),
('chesterfield coat', 'Cool'),
('Chimayo vest', 'Elegant'),
('ciao tee', 'Simple'),
('collarless coat', 'Simple'),
('college cardigan', 'Simple'),
('color-block dress shirt', 'Simple'),
('colorful striped sweater', 'Elegant'),
('comedians outfit', 'Gorgeous'),
('Coral Nook Inc. aloha shirt', 'Simple'),
('cowboy shirt', 'Simple'),
('cycling shirt', 'Active'),
('DAL apron', 'Simple'),
('DAL pilot jacket', 'Cool'),
('DAL tee', 'Simple'),
('dance-team jacket', 'Active'),
('denim jacket', 'Simple'),
('detectives coat', 'Elegant'),
('diner apron', 'Active'),
('doctors coat', 'Simple'),
('dotted raincoat', 'Cute'),
('doublet', 'Simple'),
('dress shirt', 'Simple'),
('earbuds combo', 'Cool'),
('eight-ball tee', 'Active'),
('emblem blazer', 'Elegant'),
('energetic sweater', 'Simple'),
('explorer shirt', 'Active'),
('fischerhemd', 'Simple'),
('fish-print tee', 'Simple'),
('fishing vest', 'Active'),
('fitness tank', 'Active'),
('five-ball tee', 'Active'),
('flannel shirt', 'Simple'),
('flashy cardigan', 'Gorgeous'),
('flashy jacket', 'Gorgeous'),
('football shirt', 'Active'),
('four-ball tee', 'Active'),
('frog tee', 'Active'),
('fuzzy vest', 'Simple'),
('gingham picnic shirt', 'Simple'),
('graduation gown', 'Simple'),
('Green Nook Inc. aloha shirt', 'Simple'),
('groovy shirt', 'Cool'),
('groovy tunic', 'Active'),
('guide shirt', 'Simple'),
('gym tee', 'Active'),
('hallo tee', 'Simple'),
('hand-knit tank', 'Elegant'),
('handmade cape', 'Active'),
('heart apron', 'Cute'),
('heavy-duty shirt', 'Active'),
('hello tee', 'Simple'),
('henley shirt', 'Simple'),
('hi tee', 'Simple'),
('hoi tee', 'Simple'),
('hola tee', 'Simple'),
('holiday sweater', 'Cute'),
('humble sweater', 'Simple'),
('kids smock', 'Cute'),
('konnichiwa tee', 'Simple'),
('kung-fu tee', 'Active'),
('kurta', 'Simple'),
('Labelle coat', 'Gorgeous'),
('Labelle knit shirt', 'Cool'),
('layered shirt', 'Simple'),
('military uniform', 'Elegant'),
('misty tee', 'Elegant'),
('Moms hand-knit sweater', 'Cute'),
('Moms handmade apron', 'Cute'),
('morning coat', 'Elegant'),
('mountain parka', 'Active'),
('multipurpose vest', 'Simple'),
('muscle tank', 'Active'),
('music-fest shirt', 'Active'),
('MVP tee', 'Simple'),
('ni hao tee', 'Simple'),
('nine-ball tee', 'Active'),
('No. 1 shirt', 'Simple'),
('No. 2 shirt', 'Simple'),
('No. 3 shirt', 'Simple'),
('No. 4 shirt', 'Simple'),
('noble coat', 'Gorgeous'),
('Nook Inc. aloha shirt', 'Simple'),
('Nook Inc. blouson', 'Simple'),
('Nook Inc. tee', 'Simple'),
('nurses jacket', 'Simple'),
('OK Motors jacket', 'Simple'),
('old-school jacket', 'Gorgeous'),
('one-ball tee', 'Active'),
('open-collar shirt', 'Simple'),
('peasant blouse', 'Elegant'),
('poncho-style sweater', 'Elegant'),
('princes tunic', 'Elegant'),
('printed layered shirt', 'Simple'),
('printed-sleeve sweater', 'Simple'),
('privet tee', 'Simple'),
('pullover jacket', 'Active'),
('rabbit tee', 'Active'),
('raglan shirt', 'Simple'),
('raincoat', 'Simple'),
('relay tank', 'Active'),
('royal shirt', 'Gorgeous'),
('rubber apron', 'Active'),
('safety vest', 'Active'),
('sailor-style shirt', 'Simple'),
('samurai shirt', 'Cool'),
('school jacket', 'Simple'),
('seven-ball tee', 'Active'),
('shirt with camera', 'Simple'),
('silk floral-print shirt', 'Cute'),
('silk shirt', 'Elegant'),
('simple parka', 'Simple'),
('six-ball tee', 'Active'),
('sleeved apron', 'Active'),
('soccer-uniform top', 'Active'),
('space parka', 'Cool'),
('sports tank', 'Simple'),
('staff uniform', 'Simple'),
('striped shirt', 'Simple'),
('sushi chefs outfit', 'Simple'),
('sweater on shirt', 'Elegant'),
('sweater-vest', 'Simple'),
('sweatshirt', 'Simple'),
('sweetheart tank and shirt', 'Elegant'),
('tailcoat', 'Elegant'),
('tailored jacket', 'Simple'),
('tee-parka combo', 'Simple'),
('tennis sweater', 'Simple'),
('text shirt', 'Cool'),
('thick-stripes shirt', 'Active'),
('thiefs costume', 'Cool'),
('thread-worn sweater', 'Cool'),
('three-ball tee', 'Active'),
('tie-dye shirt', 'Active'),
('tight-knit sweater', 'Simple'),
('top coat', 'Simple'),
('track jacket', 'Active'),
('traditional straw coat', 'Simple'),
('trench coat', 'Elegant'),
('tuxedo jacket', 'Cool'),
('tweed jacket', 'Elegant'),
('tweed vest', 'Simple'),
('two-ball tee', 'Active'),
('V-neck sweater', 'Simple'),
('vampire costume', 'Cool'),
('vest with binoculars', 'Simple'),
('viking top', 'Cool'),
('waistcoat', 'Simple'),
('western shirt', 'Active'),
('work apron', 'Active'),
('work shirt', 'Cool'),
('workers jacket', 'Active'),
('workout top', 'Active'),
('young-royal shirt', 'Gorgeous'),
('zigzag shirt', 'Active');

SELECT * FROM gifts;